apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xcbd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xcbd
    app.kubernetes.io/part-of: tkwch-fix-0075-0040-app
  name: devfile-sample-xcbd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xcbd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xcbd
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0040-tenant/tkwch-fix-0075-0040-app/devfile-sample-xcbd@sha256:79f058b5198b72c0cf9b7548cad2f39e050ad99937b3b91e49c03aca2c713da1
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
