apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xcbd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xcbd
    app.kubernetes.io/part-of: tkwch-fix-0075-0040-app
  name: devfile-sample-xcbd5p0n
spec:
  path: /
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: devfile-sample-xcbd
    weight: null
status: {}
